### ISSUE TITLE
`styleSheet` is `undefined`

### ISSUE THREAD

**Issue by halostatue** [arantius/web-color-wheel#1]
```javascript
const svg = document.querySelector('svg');
const style = svg.querySelector('style').sheet; // -> undefined
```

According to MDN, that will only be present for external stylesheets, and it doesn't look like the SVG has an external stylesheet. (https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet#obtaining_a_stylesheet) This is *technically* correct (the best sort, right), but the implicit stylesheet is in `document.styleSheets`, so it can be found:

```javascript
    const svg = document.querySelector('svg')
    const style = svg.querySelector('style')
    const svgStyle =
      'sheet' in style
        ? style.sheet
        : Array.from(document.styleSheets).find(function (v) {
            return v.ownerNode === style
          })
```

This seems to work in a local test.

**Comment by arantius** [comment]
The linked documentation says:

"Reason for the style sheet to be associated with the document:  <style> and \<link\> elements in the document "
"Getting the CSSStyleSheet object from the owner:  HTMLLinkElement.sheet, HTMLStyleElement.sheet, or SVGStyleElement.sheet"

In this case `svg.querySelector('style')` is a(n instance of) SVGStyleElement, so it has a `.sheet`.  LGTM.

**Comment by halostatue** [comment]
What I can say is that, on Safari 16.1, if you do `document.querySelector('svg').querySelector('style').sheet`, you get `undefined`. It may be a bug, but the `Array.from(…).find(…)` alternate flow makes the colour wheel show up.

**Comment by arantius** [comment]
Ah!  "Doesn't work in [browser X]" is different from "I interpret the standard this way".

Should be fixed but I don't have a Mac/iThing to test with.

**Comment by halostatue** [comment]
Sorry. I think I over-edited my initial message to remove references to Safari. This wasn’t a "standards interpretation", but "looks like Safari interprets this differently".
