### ISSUE TITLE
honeydew and ivory are switched

### ISSUE THREAD

**Issue by psmpm** [arantius/web-color-wheel#3]
hovering honeydew highlights ivory, and hovering ivory highlights honeydew

**Comment by arantius** [comment]
On what browser?  Any other details?  Seems to work for me.

![image](https://user-images.githubusercontent.com/84729/206879409-44cd9605-7a30-4288-93ba-faf848c50c8d.png)

(Though, ironically, some of those colors are a bit mangled, however this image got uploaded here.)

**Comment by psmpm** [comment]
I'm running firefox and it was on this blog post: https://www.joshwcomeau.com/css/color-formats/
However, going back, it seems it doesn't happen anymore. Strange.
